---
name: dummy

director_uuid: 1814d7a5-6a04-4201-adb1-d6e38cb4fb14

releases:
- {name: dummy, version: "0+dev.2"}
- {name: turbulence, version: latest}

jobs:
- name: dummy_z1
  templates:
  - {name: dummy, release: dummy}
  - {name: turbulence_agent, release: turbulence}
  instances: 3
  resource_pool: default
  networks:
  - name: default

- name: dummy2_z1
  templates:
  - {name: dummy, release: dummy}
  - {name: turbulence_agent, release: turbulence}
  instances: 1
  resource_pool: default
  networks:
  - name: default

properties:
  turbulence_agent:
    api:
      host: 10.244.8.2
      password: p
      ca_cert: |
        -----BEGIN CERTIFICATE-----
        MIIDtzCCAp+gAwIBAgIJAL+XoGqlINOLMA0GCSqGSIb3DQEBBQUAMEUxCzAJBgNV
        BAYTAkFVMRMwEQYDVQQIEwpTb21lLVN0YXRlMSEwHwYDVQQKExhJbnRlcm5ldCBX
        aWRnaXRzIFB0eSBMdGQwIBcNMTUwNzEyMDIzNTA4WhgPMjI4OTA0MjUwMjM1MDha
        MEUxCzAJBgNVBAYTAkFVMRMwEQYDVQQIEwpTb21lLVN0YXRlMSEwHwYDVQQKExhJ
        bnRlcm5ldCBXaWRnaXRzIFB0eSBMdGQwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAw
        ggEKAoIBAQDOGrPb3jitQZBPqJYC2/1rrpXO6cQF4hQV6CPajFnTYI2TmoKVrPpt
        hbJVbcWC4VopmfVrq2YLkP28L25QEtNCg8QBJOa5jLPCDzffasA40YUqrMMWOh0b
        JqzXKgtc4u0FffHBSXq3csyQXNeB/UG6qk/0YuJCFYY5zVAnOmyKdLJjngmUQovx
        ssjfcprkgOMqpPW9BSus4m945OEWqQixk0saxT1MTL3do7oGSacT30jXZV9bowlV
        COsZj+rR6IQkNYaZUWfYBPuHzEP3RN/J21F7T0KCi4q49CnkEwVsf6pnjFhIBuJ7
        u+vKQ3Gq0Yro28SJs0leE8x3OA/WnLiJAgMBAAGjgacwgaQwHQYDVR0OBBYEFNL4
        IU9fUeXBlqKwczeB3Pnup8qeMHUGA1UdIwRuMGyAFNL4IU9fUeXBlqKwczeB3Pnu
        p8qeoUmkRzBFMQswCQYDVQQGEwJBVTETMBEGA1UECBMKU29tZS1TdGF0ZTEhMB8G
        A1UEChMYSW50ZXJuZXQgV2lkZ2l0cyBQdHkgTHRkggkAv5egaqUg04swDAYDVR0T
        BAUwAwEB/zANBgkqhkiG9w0BAQUFAAOCAQEAMgANBnQbsgs9Yr0wSG1jD4w/pM90
        y7MkLjstmOC5u9kHihWk3KDoI4Bx0fXD9wbyhP/E9AikqG7SglkuViRCrtWDprEp
        8kTGbPG8sPjiu2cnmG19QcmL4HHHaG76r75qEggPu2wRGlEj0BR2zwOuINHCjfgz
        Zi8Gl/4jRAazOcXmFfnNy/RXVOwswWQOG7aKbhHWCODn7jobT95wVTouEppUw7p9
        twzPSzG7vudrmO3PSgAT+db/xrDRoHa3xk5H3fltZi7uxpRaWPqsFDezDYul4C8b
        9JpGUkpLi0wGcVfceVLiZooxVGIQTFJj8Yu6fnTM2ZbD0xwFDyrYM92uWg==
        -----END CERTIFICATE-----

resource_pools:
- name: default
  stemcell:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent
    version: latest
  network: default
  cloud_properties: {}

networks:
- name: default
  type: manual
  subnets:
  - range: 10.244.9.0/30
    reserved: [10.244.9.1]
    cloud_properties: {}
  - range: 10.244.9.4/30
    reserved: [10.244.9.5]
    cloud_properties: {}
  - range: 10.244.9.8/30
    reserved: [10.244.9.9]
    cloud_properties: {}
  - range: 10.244.9.12/30
    reserved: [10.244.9.13]
    cloud_properties: {}
  - range: 10.244.9.16/30
    reserved: [10.244.9.17]
    cloud_properties: {}
  - range: 10.244.9.20/30
    reserved: [10.244.9.21]
    cloud_properties: {}
  - range: 10.244.9.24/30
    reserved: [10.244.9.25]
    cloud_properties: {}
- name: compilation
  type: dynamic
  cloud_properties: {}

compilation:
  workers: 1
  network: compilation
  cloud_properties: {}

update:
  canaries: 1
  max_in_flight: 1
  canary_watch_time: 5000 - 20000
  update_watch_time: 5000 - 20000
